### ISSUE TITLE
Proto fails when using Python plugin

### ISSUE THREAD

**Issue by andriygm** [moonrepo/python-plugin#11]
When invoking `proto install python`, we get
```
Error: plugin::call_func::failed
  × No pre-built available for version 3.12.1!moonrepo/python-plugin/master/releases.json","headers":{},"method":null}
  │ <omitted path>"},"proto_dir":{"athZ
```

This occurs on both Mac M1 and Ubuntu 22.04.

**Comment by andriygm** [comment]
(looks like regenerating that releases.json should fix)

**Comment by andriygm** [comment]
@milesj ah interesting -- is there a different strategy that should be used for resolving the default python version then? since it's trying to pull 3.12.1 but the prebuilts don't exist for it?

**Comment by milesj** [comment]
You would need to just be explicit for now: `proto install python 3.12.0`

**Comment by rotu** [comment]
I'm sure there's a reason we're using the builds from `indygreg` but builds are also available here: https://www.python.org/downloads/release/python-3130a2/
which pulls from the official builds here:
https://www.python.org/ftp/python/

**Comment by milesj** [comment]
Those aren't pre-builts though? They're installers or require building from source yourself once unpacked (which we don't support yet).

**Comment by rotu** [comment]
Yes, it has installers (which can be extracted; e.g. a macOS `.pkg` is just a `xar`) but also the "embeddable" packages appear to be built Windows versions.

I think python.org does *not* distribute Linux binaries though. So I suppose that's a good reason the `indygreg` builds are a must.

**Comment by rotu** [comment]
I see prebuilt are also missing for 3.11.7 and I get checksum errors when trying to install latest minor versions 3.10.13, 3.9.18.

**Comment by milesj** [comment]
Yah he doesn't support everything. I'm not entirely sure how he picks which versions to support.

**Comment by milesj** [comment]
The 3.12 versions are now available.
