### ISSUE TITLE
Bin symlinks omit the major version number

### ISSUE THREAD

**Issue by rotu** [moonrepo/python-plugin#12]
`proto install python <version>` creates symlinks in `bin` with the minor version but omitting the major version. e.g. 
- `python.9` -> `.proto/tools/python/3.9.17/install/bin/python3.9`
- `python.10` -> `.proto/tools/python/3.10.12/install/bin/python3.10`
- `python.11` -> `.proto/tools/python/3.11.6/install/bin/python3.11`

Proto 0.25.3 on macOS

**Comment by milesj** [comment]
This shouldn't even include the version number at all...

**Comment by milesj** [comment]
Has to be fixed on the proto side, will do here: https://github.com/moonrepo/proto/pull/354
