### ISSUE TITLE
proto install python seems to always fail

### ISSUE THREAD

**Issue by rotu** [moonrepo/python-plugin#3]
`proto install python` failed for me on macOS with `pyenv` installed. The below output shows multiple issues.

- It's not obvious that the [presence of `pyenv`](https://github.com/moonrepo/python-plugin/blob/f401604265d274d8be0e54eb43b3662c1d4e85c7/src/proto.rs#L32-L34) should affect whether to install prebuilt or build from source. This is documented [in the readme](https://github.com/moonrepo/python-plugin/blob/68525fe9dc1a62ef2b5a5f2a810f25e082c11721/README.md#caveats) but probably should be part of the tool output.
- I don't know why it installs to a temporary directory.
- The "timeout" error is odd, especially after indicated it *did* install the tool (and there is indeed a resulting python binary in that directory)

Uninstalling `pyenv` first seems to allow `proto install python` to succeed.

```
proto install python       
━━━        Installing Python 3.12.0                                             python-build: use openssl@3 from homebrew
python-build: use readline from homebrew
━━━━       Installing Python 3.12.0                                             Downloading Python-3.12.0.tar.xz...
-> https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tar.xz
━          Installing Python 3.12.0                                             Installing Python-3.12.0...
━━         Installing Python 3.12.0                                             python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use ncurses from homebrew
━━━━━━━━   Installing Python 3.12.0                                             Installed Python-3.12.0 to /Users/dan/.proto/temp/python/3.12.0-1697857960155
Error: plugin::failed

  × "timeout"
```

**Comment by milesj** [comment]
> It's not obvious that the [presence of pyenv](https://github.com/moonrepo/python-plugin/blob/f401604265d274d8be0e54eb43b3662c1d4e85c7/src/proto.rs#L32-L34) should affect whether to install prebuilt or build from source. This is documented [in the readme](https://github.com/moonrepo/python-plugin/blob/68525fe9dc1a62ef2b5a5f2a810f25e082c11721/README.md#caveats) but probably should be part of the tool output.

We do log stuff, but it's hidden behind debug logs. Logging from WASM isn't super straight forward.

But I agree. This is kind of a stopgap until proto upstream officially supports "build from source" as an explicit option.

> I don't know why it installs to a temporary directory.

All tools are installed to a temp directory then moved.

> The "timeout" error is odd, especially after indicated it did install the tool (and there is indeed a resulting python binary in that directory)

This one is definitely odd. That errors coming from extism directly, which is the WASM runtime. Let me see if I can bump the timeout.

**Comment by rotu** [comment]
> All tools are installed to a temp directory then moved.

Hmm... I tried to move it manually from the temp directory to the actual install directory and got the below. So moving might not suffice:

```
dyld[94988]: Library not loaded: /Users/dan/.proto/temp/python/3.12.0-1697861311929/lib/libpython3.12.dylib
  Referenced from: <5CF5F279-1BBB-3F54-A94F-662D0E57D4F4> /Users/dan/.proto/tools/python/3.12.0/install/bin/python3.12
  Reason: tried: '/Users/dan/.proto/temp/python/3.12.0-1697861311929/lib/libpython3.12.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/dan/.proto/temp/python/3.12.0-1697861311929/lib/libpython3.12.dylib' (no such file), '/Users/dan/.proto/temp/python/3.12.0-1697861311929/lib/libpython3.12.dylib' (no such file)
```

> This one is definitely odd. That errors coming from extism directly, which is the WASM runtime. Let me see if I can bump the timeout.

I measured the timeout at 73 seconds, which seems too short. But also it seems like it didn't abort the build, so the timeout is somewhat useless even if something hangs. Here's the trace output:

```
Installed Python-3.12.0 to /Users/dan/.proto/temp/python/3.12.0-1697861311929
━━━━━━━    Installing Python 3.12.0                                                           [TRACE 23:09:56] proto_wasm::exec_command:install  Executed command from plugin  command="python-build" exit_code=0 stderr_len=0 stdout_len=0
[TRACE 23:09:56] starbase::app  Running shutdown phase with 1 systems 
Error: plugin::failed

  × "timeout"
```

**Comment by milesj** [comment]
Well that's not good, I'll disable `python-build` for now.
